import type { DocumentType } from '@/lib/types'
import type { AssessmentData } from '../assessment-data'

import { generateInfoSecurityPolicy } from './info-security-policy'
import { generateScopeStatement } from './scope-statement'
import { generateRolesResponsibilitiesMatrix } from './roles-responsibilities-matrix'
import { generateRiskAssessmentMethodology } from './risk-assessment-methodology'
import { generateRiskRegister } from './risk-register'
import { generateRiskTreatmentPlan } from './risk-treatment-plan'
import { generateSoaLite } from './soa-lite'
import { generateAccessControlPolicy } from './access-control-policy'
import { generateAcceptableUsePolicy } from './acceptable-use-policy'
import { generateIncidentResponseProcedure } from './incident-response-procedure'
import { generateBusinessContinuityOverview } from './business-continuity-overview'
import { generateImplementationChecklist } from './implementation-checklist'

export type TemplateGenerator = (data: AssessmentData) => string

export const TEMPLATE_GENERATORS: Record<DocumentType, TemplateGenerator> = {
  info_security_policy: generateInfoSecurityPolicy,
  scope_statement: generateScopeStatement,
  roles_responsibilities_matrix: generateRolesResponsibilitiesMatrix,
  risk_assessment_methodology: generateRiskAssessmentMethodology,
  risk_register: generateRiskRegister,
  risk_treatment_plan: generateRiskTreatmentPlan,
  soa_lite: generateSoaLite,
  access_control_policy: generateAccessControlPolicy,
  acceptable_use_policy: generateAcceptableUsePolicy,
  incident_response_procedure: generateIncidentResponseProcedure,
  business_continuity_overview: generateBusinessContinuityOverview,
  implementation_checklist: generateImplementationChecklist,
}

// Shared HTML wrapper for all documents
export function wrapHtml(title: string, content: string, orgName: string, date: string): string {
  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>${escapeHtml(title)} - ${escapeHtml(orgName)}</title>
  <style>
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
      line-height: 1.6;
      color: #1a1a1a;
      max-width: 800px;
      margin: 0 auto;
      padding: 40px 20px;
    }
    .header {
      border-bottom: 2px solid #2563eb;
      padding-bottom: 20px;
      margin-bottom: 30px;
    }
    .header h1 {
      margin: 0 0 8px 0;
      color: #1e40af;
      font-size: 24px;
    }
    .header .org-name {
      font-size: 18px;
      color: #4b5563;
      margin: 0;
    }
    .header .date {
      font-size: 14px;
      color: #6b7280;
      margin-top: 8px;
    }
    h2 {
      color: #1e40af;
      font-size: 18px;
      margin-top: 30px;
      margin-bottom: 15px;
      border-bottom: 1px solid #e5e7eb;
      padding-bottom: 8px;
    }
    h3 {
      color: #374151;
      font-size: 16px;
      margin-top: 20px;
      margin-bottom: 10px;
    }
    p {
      margin: 10px 0;
    }
    ul, ol {
      margin: 10px 0;
      padding-left: 25px;
    }
    li {
      margin: 6px 0;
    }
    table {
      width: 100%;
      border-collapse: collapse;
      margin: 15px 0;
    }
    th, td {
      border: 1px solid #d1d5db;
      padding: 10px 12px;
      text-align: left;
    }
    th {
      background: #f3f4f6;
      font-weight: 600;
    }
    .status-yes { color: #059669; }
    .status-no { color: #dc2626; }
    .status-na { color: #6b7280; font-style: italic; }
    .placeholder {
      color: #9ca3af;
      font-style: italic;
    }
    .footer {
      margin-top: 50px;
      padding-top: 20px;
      border-top: 1px solid #e5e7eb;
      font-size: 12px;
      color: #6b7280;
    }
  </style>
</head>
<body>
  <div class="header">
    <h1>${escapeHtml(title)}</h1>
    <p class="org-name">${escapeHtml(orgName)}</p>
    <p class="date">Generated: ${escapeHtml(date)}</p>
  </div>
  ${content}
  <div class="footer">
    <p>This document was auto-generated by Voyu ISO 27001 Readiness Platform.</p>
    <p>Document Version: 1.0 | Classification: Internal</p>
  </div>
</body>
</html>`
}

export function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#039;')
}

export function statusClass(value: boolean | null | string): string {
  if (value === true || value === 'Yes') return 'status-yes'
  if (value === false || value === 'No') return 'status-no'
  return 'status-na'
}
