import { redirect, notFound } from 'next/navigation'
import Link from 'next/link'
import { createClient } from '@/lib/supabase/server'
import type { Document } from '@/lib/types'

interface Props {
  params: { id: string }
}

export default async function DocumentDetailPage({ params }: Props) {
  const supabase = createClient()

  const { data: { user } } = await supabase.auth.getUser()
  if (!user) redirect('/login')

  const { data: workspace } = await supabase
    .from('workspaces')
    .select('id')
    .eq('user_id', user.id)
    .single()

  if (!workspace) redirect('/onboarding')

  // Get document (RLS ensures user can only access their own)
  const { data: document } = await supabase
    .from('documents')
    .select('*')
    .eq('id', params.id)
    .single<Document>()

  if (!document) {
    notFound()
  }

  // Verify ownership
  if (document.workspace_id !== workspace.id) {
    notFound()
  }

  if (document.status !== 'ready' || !document.content_html) {
    return (
      <main className="min-h-screen p-8">
        <div className="max-w-4xl mx-auto">
          <Link
            href="/documents"
            className="text-sm text-gray-500 hover:text-gray-700 mb-4 inline-block"
          >
            &larr; Back to Documents
          </Link>
          <h1 className="text-2xl font-bold text-gray-900 mb-4">{document.title}</h1>
          <div className="p-8 bg-gray-50 rounded-lg text-center">
            <p className="text-gray-600">
              {document.status === 'failed'
                ? `Document generation failed: ${document.error_message}`
                : 'Document is not ready yet.'}
            </p>
          </div>
        </div>
      </main>
    )
  }

  return (
    <main className="min-h-screen bg-gray-100">
      <div className="max-w-5xl mx-auto p-8">
        <div className="flex items-center justify-between mb-4">
          <Link
            href="/documents"
            className="text-sm text-gray-500 hover:text-gray-700"
          >
            &larr; Back to Documents
          </Link>
          <div className="flex items-center gap-4">
            <span className="px-2 py-1 text-xs font-medium bg-green-100 text-green-800 rounded">
              Ready
            </span>
          </div>
        </div>

        <div className="bg-white rounded-lg shadow-lg overflow-hidden">
          <div className="p-4 bg-gray-50 border-b border-gray-200 flex items-center justify-between">
            <h1 className="font-semibold text-gray-900">{document.title}</h1>
            <span className="text-sm text-gray-500">
              Generated: {new Date(document.generated_at!).toLocaleDateString()}
            </span>
          </div>

          {/* Safe HTML rendering - content is generated by our templates only */}
          <div
            className="document-preview"
            dangerouslySetInnerHTML={{ __html: document.content_html }}
          />
        </div>
      </div>
    </main>
  )
}
